name: habit_heroes
description: A gamified family habit-tracking app.
publish_to: "none"

version: 0.2.0

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: 3.35.4

dependencies:
  auto_route: ^10.2.0
  bloc_concurrency: ^0.3.0
  collection: ^1.19.0
  cupertino_icons: ^1.0.8
  email_validator: ^3.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_colorpicker: ^1.1.0
  flutter_launcher_icons: ^0.14.4
  forui: 0.16.0
  forui_assets: ^0.16.0
  gap: ^3.0.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  mixpanel_flutter: ^2.3.3
  recase: ^4.1.0
  sentry_flutter: ^8.13.2
  sentry_logging: ^8.13.2
  slang_flutter: ^4.9.0
  supabase_flutter: 2.10.3
  google_fonts: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^10.2.5
  build_runner: ^2.4.14
  flutter_test:
    sdk: flutter
  golden_toolkit: ^0.15.0
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  slang: ^4.9.2
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
